# Generated by Django 6.0.3 on 2026-04-04 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hasta_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Detailed product description"),
                ),
                (
                    "image_path",
                    models.CharField(
                        help_text="Path to product image (e.g., 'images/gallery12.jpeg')",
                        max_length=300,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Available stock units"
                    ),
                ),
                (
                    "average_rating",
                    models.FloatField(
                        default=0.0,
                        help_text="Average rating from 0 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of reviews/ratings"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clip", "Hair Clip"),
                            ("keyring", "Keyring"),
                            ("flower", "Flower"),
                            ("toy", "Toy"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Product category",
                        max_length=100,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        default="Yarn",
                        help_text="Material used (e.g., Yarn, Cotton)",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Primary color of the product",
                        max_length=100,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="Product size (e.g., Small, Medium, Large)",
                        max_length=50,
                    ),
                ),
                (
                    "handmade",
                    models.BooleanField(
                        default=True, help_text="Is this product handmade?"
                    ),
                ),
                (
                    "customizable",
                    models.BooleanField(
                        default=False, help_text="Can this product be customized?"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this product on homepage"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this product available for sale?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
    ]
