# Generated by Django 5.0.1 on 2026-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta_app', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file for this product', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, help_text="Fallback path to product image (e.g., 'images/gallery12.jpeg')", max_length=300, null=True),
        ),
    ]
